title: Welcome to Niro's Page
logo: [https://github.com/NiroseDavid/NiroseDavid.github.io/blob/main/E-Shoot-96.JPG]
description: [A short description of your site's purpose]
theme: jekyll-theme-minimal
